name: 'Generate graph from usage statistics'
on:
  push:
    branches:
      - generate-usage-statistics-graph
  schedule:
    - cron:  '0 0 * * *'

jobs:
  graph-generation-job:
    runs-on: ubuntu-18.04
    name: Generate graph from usage statistics.
    steps:
      - uses: actions/checkout@v1
      - name: Run graph generation utility action
        uses: ./.github/actions/statistics-graph-action
        with:
          service-account-credentials: ${{ secrets.GMAIL_SERVICE_ACCOUNT_CREDENTIALS }}