name: 'Generate chart from usage statistics data'
on:
  push:
    branches:
      - generate-usage-statistics-graph
  schedule:
    - cron:  '0 0 * * *'

jobs:
  graph-generation-job:
    runs-on: ubuntu-18.04
    name: Generate chart from usage statistics data.
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "master"
      - name: Run chart generation utility action
        uses: ./.github/actions/statistics-chart-action
        with:
          firebase-service-account-email: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMAIL }}
          firebase-service-account-private-key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY }}
      - uses: actions/upload-artifact@v1
        with:
          name: charts
          path: chart-output/
      - run: mv chart-output/* usage-statistics-charts/
      - run: git add usage-statistics-charts/
      - run: git config user.email "maierjonas@live.de"
      - run: git config user.name "maierj"
      - run: git diff --staged --quiet || git commit -m "Generate usage statistics charts"
      - run: ssh-agent bash -c 'ssh-add - <<< "${DEPLOY_KEY}"; git push'
        env:
          DEPLOY_KEY: ${{ secrets.USAGE_STATISTICS_CHARTS_DEPLOY_KEY }}